### ISSUE TITLE
Scaling issue when using markcorr_anisotropic in rectangular instead of (unit) cubic box

### ISSUE THREAD

**Issue by chamche** [antiphon/Kdirectional#1]
This simulated marked point pattern in a rectangular instead of (unit) cubic box exemplifies the issue:

``` r
library(rstrauss)
bbox <- rbind(c(0,0,0),c(5,5,1))
set.seed(11)
x <- rstrauss(45, gamma = .1, range =.1, bbox = bbox, perfect=T, iter=1e5)
# attach z-coordinates as marks
m <- x$x[,3]
mcor3 <- markcorr_anisotropic(x, marks=m, r = seq(0, .3, l=50))
# plot shows the scaling issue for x and y directions
par(mfrow=c(1,3))
for(i in 1:3) plot(mcor3$r, mcor3$mcor[,i], type="l")
```

**Comment by antiphon** [comment]
After some thought and testing, I'm not sure there is a problem with the implementation but with the directed mark-correlation idea itself. To begin with, the pcf's seem to be ok i.e. strong repulsion upto .1 and then settle to about 1:

``` r
for(i in 1:3) plot(mcor3$r, mcor3$pcf[,i], type="l")
```

One potential issue in this example is that the very strong structure in the marking `m <- x$x[,3]` will be present in all direction due to angular smoothing.

I'll leave the issue open for now.

**Comment by antiphon** [comment]
Not a code problem, closing the issue.
